#ifndef PLATFORM_OPTIONS_H
#define PLATFORM_OPTIONS_H

#define PROGRAM_TITLE "Breakout"
#define PROGRAM_WIDTH 1280
#define PROGRAM_HEIGHT 720

#define PERMANENT_MEMORY_SIZE megabytes(64)
#define FRAME_MEMORY_SIZE     megabytes(1)

#endif //PLATFORM_OPTIONS_H
